### ISSUE TITLE
Reader not loading within Twitter in-app browser

### ISSUE THREAD

**Issue by bdfinlayson** [futurepress/epub.js#318] opened 2015-11-15 02:30 UTC
`EPUBJS.Render.Iframe.prototype.load` appears to be failing in Twitter's in-app browser. Does anyone have any insights into what might be causing this problem? Sorry but I have no stack trace or errors to provide.

In a normal browser, our markup is rendered as follows: 

     <iframe id="epubjs-iframe:dae55d8b-6b9c-43f5-aa33-8653c73a85e1" scrolling="no" height="169" width="1140" style="border: none; visibility: visible;"></iframe>
       <html xmlns="http://www.w3.org/1999/xhtml" style="overflow: hidden; width: 112674px; height: 169px; -webkit-column-gap: 142px; -webkit-column-width: 499px;"><head><title> </title><meta http-equiv="Content-Style-Type" content="text/css"><meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8"><link rel="stylesheet" type="text/css" href="blob:http%3A//localhost%3A3000/5499d993-b4f2-4b15-840f-57480eb5e57b">
      <meta content="" name="">
      </head>
        <body style="margin: 0px;"><p id="id00000">The Project Gutenberg EBook of Poems, by Marietta Holley</p>
          <p> Additional text here.... </p>
        </body>
      </html>
    </iframe>

**Comment by fchasen** [comment] 2015-11-18 01:21
Hard to know what the issue could be but I wonder if it is cross origin related.

**Comment by fchasen** [comment] 2015-12-03 19:25
Going to close this for now, but happy to reopen if was can figure out what the issue is.
Would be happy to discuss more on gitter.

**Closed by fchasen** 2015-12-03 19:25 UTC
