### ISSUE TITLE
How to display always two pages in fixed layout

### ISSUE THREAD

**Issue by avstudios** [futurepress/epub.js#433] opened 2016-06-23 08:07 UTC
Hi, I have illustrated books and I want to always display two pages. Is it possible? I've tried layoutOveride, fixedLayout, spreads, minSpreadWidth params but nothing made it work. I can't find any example how to do it. I would be grateful for any help.

**Comment by ssomnoremac** [comment] 2016-06-23 13:27
This is a duplicate of #376  You are in luck though as I've gotten this to work but in a somewhat hackish manner on v3, using the inline branch. I don't know when I'll make a proper factor of my code for a PR but I am creating a `DoubleViewManager` that inherits from `SingleViewManager` and creating a second view (page) with `section.next()` when appropriate. I'll issue a PR with my initial code soon.

**Comment by JakeHartnell** [comment] 2016-06-29 20:03
Closing as this is a duplicate.

**Closed by JakeHartnell** 2016-06-29 20:03 UTC
