### ISSUE TITLE
Updating the Hypothes.is example

### ISSUE THREAD

**Issue by BigBlueHat** [futurepress/epub.js#157] opened 2014-08-26 20:01 UTC
I'm interested in helping resurrect the hypothes.is integration example and make sure we help keep it up to date (full disclosure: I work there :smile_cat: ).

A couple things of note:
 - we now bundle all our JS & CSS assets
 - we handle the loading of them via `embed.js`

Beyond that, I'd love to get a sense of what might be needed to catch back up with epub.js and then chart a course for us staying more in sync.

Thanks!

**Comment by JakeHartnell** [comment] 2015-08-12 09:37
This is a duplicate of #157

**Closed by JakeHartnell** 2015-08-12 09:37 UTC
