### ISSUE TITLE
Can not load a book from manifest.json

### ISSUE THREAD

**Issue by miendinh** [futurepress/epub.js#822] opened 2018-09-12 07:02 UTC
I tried epub.js 0.3.66 with this examples

1. https://github.com/futurepress/epub.js/blob/master/examples/manifest.html
2. https://s3.amazonaws.com/epubjs-manifest/examples/manifest.html?href=https://readium2.now.sh/pub/L2hvbWUvbm93dXNlci9zcmMvbWlzYy9lcHVicy9jaGlsZHJlbnMtbGl0ZXJhdHVyZS5lcHVi/manifest.json

they seem not to work and don't show any error logs.

are there any bugs in v.0.3.66 ?

thanks

**Comment by danielweck** [comment] 2018-09-29 07:28
Note that the latest "Readium webpub manifest" specification introduced a breaking change: 'spine' was renamed 'readingOrder' (to align with W3C Web Publications)

The r2-streamer-js server generates this new syntax, so every existing reading system (such as EPUBjs) that implements support for the Readium JSON manifest must update their code accordingly.

Could this be the root cause of the problem here?

CC @JayPanoz

**Comment by danielweck** [comment] 2018-09-29 07:35
Yes, it looks like the EPUBjs code looks for 'spine' instead of 'readingOrder' when parsing the manifest JSON:

'this.spine = json.spine.map( ... )'

https://github.com/futurepress/epub.js/blob/v0.4/src/epub/packaging.js

**Comment by danielweck** [comment] 2018-09-29 07:37
CC @HadrienGardeur

Note that the 'webpub-viewer' demo must be updated too:

'manifest.spine.map( ... )'

https://github.com/HadrienGardeur/webpub-viewer/blob/master/viewer.js.

**Comment by danielweck** [comment] 2018-09-29 07:39
@JCCR is the EvidentPoint reader up to date with respect to the 'spine' vs. 'readingOrder' renaming?

**Comment by danielweck** [comment] 2018-09-29 07:49
@jccr 
if I am not mistaken you guys rely on the TypeScript ta-json (de)serialisation framework from r2-shared-js models, so you should "automatically" be up to date next time you synchronize with the upstream code.

https://github.com/evidentpoint/r2-shared-js/blob/develop/src/models/publication.ts

https://github.com/evidentpoint/r2-navigator-web/blob/master/src/streamer/publication.ts

**Comment by danielweck** [comment] 2018-09-29 07:59
Fred (@futurepress), sorry to populate this issue with a global status update on "webpub manifest" support, but I think it is important that we achieve interoperability across reading systems. My apologies if this is off-the-mark.

@NYPL-Simplified

Same problem here:
'this.spine = manifestJSON.spine'

https://github.com/NYPL-Simplified/webpub-viewer/blob/master/src/Manifest.ts

I think the best move forward is to implement backward-compatible JSON parsing ('spine' *and* 'readingOrder'), because not all instances of Readium 2 "streamer" serve the updated webpub manifest syntax, and some integrations might still be using an old r2-streamer-js revision.

@HadrienGardeur, what do you think?

**Comment by JayPanoz** [comment] 2018-09-29 08:41
FWIW, that’s what I was going to (temporarily?) do indeed as we’re in server update mode right now and supporting both is not too much overhead – while providing some flexibility just in case we need to roll back for some reason.

**Comment by fchasen** [comment] 2018-09-30 04:41
@danielweck - Thanks for bring this to my attention!

I've updated v0.3 & v0.4 to use either `manifest.readingOrder` or `manifest.spine` but I still need to figure out if I should rename all the spine related methods / classes. I've always like the term.

Will publish to npm after that is sorted.

**Comment by JayPanoz** [comment] 2018-10-01 15:38
@danielweck done in our NYPL fork, no issue to report – thanks again for helping by mail. 👍

**Comment by danielweck** [comment] 2018-10-03 07:36
Thanks for the quick fix @fchasen :)

Note that the demo page:
https://s3.amazonaws.com/epubjs-manifest/examples/manifest.html?href=https://readium2.now.sh/pub/L2hvbWUvbm93dXNlci9zcmMvbWlzYy9lcHVicy9jaGlsZHJlbnMtbGl0ZXJhdHVyZS5lcHVi/manifest.json

...has not been updated with the latest code yet:
https://github.com/futurepress/epub.js/commit/7fd362bb822beeb7008d12e65be92190e1defc57

**Comment by danielweck** [comment] 2018-10-03 07:45
@HadrienGardeur I created a PR: https://github.com/HadrienGardeur/webpub-viewer/pull/7

**Comment by danielweck** [comment] 2018-10-03 07:49
@NYPL-Simplified I crated a PR: https://github.com/NYPL-Simplified/webpub-viewer/pull/139

**Comment by fchasen** [comment] 2018-10-14 01:06
Updated the demo, going to close this for now.

Thanks all!

**Closed by fchasen** 2018-10-14 01:06 UTC
