### ISSUE TITLE
Problem with some books on Ipad/Iphone

### ISSUE THREAD

**Issue by bahinapster** [futurepress/epub.js#231] opened 2015-07-16 14:22 UTC
Hello ,
I have an issue with some books on ipad and iphone where the reader crache after one or two paginations.
+ The pages size is not correct

PS: (moby-dick) works very good

**Comment by JakeHartnell** [comment] 2015-08-12 09:06
@bahinapster I'm closing this issue because there is not enough information to reproduce. Feel free to reopen with more details.

**Closed by JakeHartnell** 2015-08-12 09:06 UTC
